document.addEventListener('DOMContentLoaded', () => { renderLayout('Purchase Orders'); VB.requireRole(['Procurement Officer']); renderPOs(); });
function renderPOs() {
  const pos = POService.getAll(), invoices = InvoiceService.getAll(), root = document.getElementById('poRoot');
  root.innerHTML = pos.length ? `<div class="table-wrapper"><table><thead><tr><th>PO Number</th><th>Vendor Name</th><th>Item Description</th><th>Quantity</th><th>Unit Price</th><th>Subtotal</th><th>GST Amount</th><th>Grand Total</th><th>Status</th><th>Date</th><th>Actions</th></tr></thead><tbody>${pos.map(p=>`<tr><td>${p.poNumber}</td><td>${p.vendorName}</td><td>${p.itemDescription}</td><td>${p.quantity} ${p.unit}</td><td>${VB.money(p.unitPrice)}</td><td>${VB.money(p.subtotal)}</td><td>${VB.money(p.gst)}</td><td>${VB.money(p.grandTotal)}</td><td>${VB.badge(p.status)}</td><td>${VB.date(p.date)}</td><td><div class="actions"><button class="btn btn-sm btn-outline" onclick="viewPO('${p.id}')">View PO</button>${invoices.some(i=>i.poId===p.id)?'':`<button class="btn btn-sm btn-primary" onclick="generateInvoice('${p.id}')">Generate Invoice</button>`}</div></td></tr>`).join('')}</tbody></table></div>` : `<div class="card empty-state"><span class="icon">📦</span>No purchase orders generated yet.</div>`;
}
function poDoc(p) {
  return `<div class="doc-layout"><div class="doc-header"><div><h2>VendorBridge</h2><p>Procurement Office<br>India</p></div><div><h2>${p.poNumber}</h2><p>${VB.date(p.date)}</p>${VB.badge(p.status)}</div></div><div class="doc-cols"><div><h3>Bill From</h3><p>VendorBridge Procurement<br>Corporate Office<br>procurement@vendorbridge.com</p></div><div><h3>Bill To</h3><p>${p.vendorName}<br>GST: ${p.vendorGst}<br>${p.vendorEmail}<br>${p.vendorPhone}<br>${p.vendorAddress}</p></div></div><table><thead><tr><th>Sr No</th><th>Item Description</th><th>Quantity</th><th>Unit</th><th>Unit Price</th><th>Amount</th></tr></thead><tbody><tr><td>1</td><td>${p.itemDescription}</td><td>${p.quantity}</td><td>${p.unit}</td><td>${VB.money(p.unitPrice)}</td><td>${VB.money(p.subtotal)}</td></tr></tbody></table><div class="totals"><div><span>Subtotal</span><strong>${VB.money(p.subtotal)}</strong></div><div><span>GST 18%</span><strong>${VB.money(p.gst)}</strong></div><div class="grand"><span>Grand Total</span><strong>${VB.money(p.grandTotal)}</strong></div></div><p><strong>Terms and Conditions:</strong> Goods and services must match the accepted quotation and delivery schedule.</p><p style="text-align:right;margin-top:40px">Authorized Signature</p></div>`;
}
function viewPO(id) { const p = POService.getById(id); VB.modal('Purchase Order', poDoc(p), `<button class="btn btn-outline" data-close>Close</button><button class="btn btn-primary" onclick="window.print()">Print</button>`, true); }
function generateInvoice(id) { const po = POService.getById(id), inv = InvoiceService.generateFromPO(po), u = VB.currentUser(); LogService.add(u.id,u.name,u.role,`Invoice generated: ${inv.invoiceNumber}`,'Invoices'); VB.toast('Invoice generated'); window.location.href = 'invoices.html'; }
