let vendorSearch = '';
document.addEventListener('DOMContentLoaded', () => { renderLayout('Vendor Management'); VB.requireRole(['Admin','Procurement Officer']); renderVendors(); });
function renderVendors() {
  const root = document.getElementById('vendorsRoot');
  const vendors = VendorService.getAll().filter(v => [v.name, v.category].join(' ').toLowerCase().includes(vendorSearch.toLowerCase()));
  root.innerHTML = `<div class="page-toolbar"><div class="toolbar-left"><input class="form-control" id="vendorSearch" placeholder="Search vendor or category" value="${vendorSearch}"></div><div class="toolbar-right"><button class="btn btn-primary" id="addVendor">Add Vendor</button></div></div>${vendors.length ? `<div class="table-wrapper"><table><thead><tr><th>Sr No</th><th>Vendor Name</th><th>Category</th><th>GST Number</th><th>Contact Email</th><th>Phone</th><th>Status</th><th>Actions</th></tr></thead><tbody>${vendors.map((v,i)=>`<tr><td>${i+1}</td><td>${v.name}</td><td>${v.category}</td><td>${v.gst}</td><td>${v.email}</td><td>${v.phone}</td><td>${VB.badge(v.status)}</td><td><div class="actions"><button class="btn btn-sm btn-outline" onclick="openVendorModal('${v.id}')">Edit</button><button class="btn btn-sm btn-danger" onclick="deleteVendor('${v.id}')">Delete</button><button class="btn btn-sm btn-warning" onclick="toggleVendor('${v.id}')">Toggle Status</button></div></td></tr>`).join('')}</tbody></table></div>` : `<div class="card empty-state"><span class="icon">🏢</span>No vendors registered yet. Click Add Vendor to get started.</div>`}`;
  document.getElementById('vendorSearch').oninput = e => { vendorSearch = e.target.value; renderVendors(); };
  document.getElementById('addVendor').onclick = () => openVendorModal();
}
function openVendorModal(id) {
  const v = id ? VendorService.getById(id) : { status: 'Active', category: 'Electronics' };
  const body = `<form id="vendorForm"><div class="form-group"><label class="form-label">Vendor Name</label><input class="form-control" id="vName" value="${v.name || ''}" required></div><div class="form-group"><label class="form-label">Category</label><select class="form-control" id="vCategory">${['Electronics','IT Services','Office Supplies','Logistics','Construction','Other'].map(c=>`<option ${v.category===c?'selected':''}>${c}</option>`).join('')}</select></div><div class="form-group"><label class="form-label">GST Number</label><input class="form-control" id="vGst" value="${v.gst || ''}" required></div><div class="form-group"><label class="form-label">Contact Person Name</label><input class="form-control" id="vContact" value="${v.contactPerson || ''}"></div><div class="form-group"><label class="form-label">Email</label><input class="form-control" id="vEmail" type="email" value="${v.email || ''}" required></div><div class="form-group"><label class="form-label">Phone</label><input class="form-control" id="vPhone" value="${v.phone || ''}" required></div><div class="form-group"><label class="form-label">Address</label><textarea class="form-control" id="vAddress">${v.address || ''}</textarea></div><div class="vendor-status-row"><label><input type="radio" name="vStatus" value="Active" ${v.status !== 'Inactive' ? 'checked' : ''}> Active</label><label><input type="radio" name="vStatus" value="Inactive" ${v.status === 'Inactive' ? 'checked' : ''}> Inactive</label></div></form>`;
  const overlay = VB.modal(id ? 'Edit Vendor' : 'Add Vendor', body, `<button class="btn btn-outline" data-close>Cancel</button><button class="btn btn-primary" id="saveVendor">Save</button>`);
  overlay.querySelector('#saveVendor').onclick = () => {
    const gst = vGst.value.trim(), phone = vPhone.value.trim();
    if (!vName.value.trim() || !/^[0-9A-Z]{15}$/.test(gst) || !/^\d{10}$/.test(phone) || !vEmail.value.trim()) { VB.toast('Please enter valid vendor details.', 'danger'); return; }
    const data = { name: vName.value.trim(), category: vCategory.value, gst, contactPerson: vContact.value.trim(), email: vEmail.value.trim(), phone, address: vAddress.value.trim(), status: overlay.querySelector('input[name="vStatus"]:checked').value };
    id ? VendorService.update(id, data) : VendorService.add(data);
    const u = VB.currentUser(); LogService.add(u.id, u.name, u.role, id ? `Vendor updated: ${data.name}` : `Vendor created: ${data.name}`, 'Vendors');
    overlay.remove(); VB.toast('Vendor saved successfully'); renderVendors();
  };
}
function deleteVendor(id) { VB.confirm('Delete Vendor', 'Are you sure you want to delete this vendor?', () => { const v = VendorService.getById(id), u = VB.currentUser(); VendorService.delete(id); LogService.add(u.id,u.name,u.role,`Vendor deleted: ${v.name}`,'Vendors'); VB.toast('Vendor deleted'); renderVendors(); }, true); }
function toggleVendor(id) { const v = VendorService.toggleStatus(id), u = VB.currentUser(); LogService.add(u.id,u.name,u.role,`Vendor status changed: ${v.name} is ${v.status}`,'Vendors'); VB.toast('Vendor status updated'); renderVendors(); }
